version: '3.8'

services:
  # Django web application
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DATABASE_URL=postgresql://django_user:django_password@db:5432/django_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here-for-development-only
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpassword

  # Celery worker
  celery:
    build: .
    command: celery -A django_celery_base worker --loglevel=info
    restart: always
    depends_on:
      - web
      - redis
      - db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DATABASE_URL=postgresql://django_user:django_password@db:5432/django_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here-for-development-only

  # Redis service for Celery
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  # React frontend
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: